// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyProtoBuff.proto

package rest.api.proto;

public final class ProtoBuffImpl {
  private ProtoBuffImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MyProtoBuffOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.student.MyProtoBuff)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string className = 1;</code>
     */
    java.lang.String getClassName();
    /**
     * <code>string className = 1;</code>
     */
    com.google.protobuf.ByteString
        getClassNameBytes();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 3;</code>
     */
    int getAge();

    /**
     * <pre>
     * string[] courses = 4;
     * </pre>
     *
     * <code>repeated string course = 5;</code>
     */
    java.util.List<java.lang.String>
        getCourseList();
    /**
     * <pre>
     * string[] courses = 4;
     * </pre>
     *
     * <code>repeated string course = 5;</code>
     */
    int getCourseCount();
    /**
     * <pre>
     * string[] courses = 4;
     * </pre>
     *
     * <code>repeated string course = 5;</code>
     */
    java.lang.String getCourse(int index);
    /**
     * <pre>
     * string[] courses = 4;
     * </pre>
     *
     * <code>repeated string course = 5;</code>
     */
    com.google.protobuf.ByteString
        getCourseBytes(int index);
  }
  /**
   * Protobuf type {@code proto.student.MyProtoBuff}
   */
  public  static final class MyProtoBuff extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.student.MyProtoBuff)
      MyProtoBuffOrBuilder {
    // Use MyProtoBuff.newBuilder() to construct.
    private MyProtoBuff(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyProtoBuff() {
      className_ = "";
      name_ = "";
      age_ = 0;
      course_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MyProtoBuff(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              className_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              age_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                course_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              course_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          course_ = course_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rest.api.proto.ProtoBuffImpl.internal_static_proto_student_MyProtoBuff_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rest.api.proto.ProtoBuffImpl.internal_static_proto_student_MyProtoBuff_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rest.api.proto.ProtoBuffImpl.MyProtoBuff.class, rest.api.proto.ProtoBuffImpl.MyProtoBuff.Builder.class);
    }

    private int bitField0_;
    public static final int CLASSNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object className_;
    /**
     * <code>string className = 1;</code>
     */
    public java.lang.String getClassName() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        className_ = s;
        return s;
      }
    }
    /**
     * <code>string className = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <code>int32 age = 3;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int COURSE_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList course_;
    /**
     * <pre>
     * string[] courses = 4;
     * </pre>
     *
     * <code>repeated string course = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getCourseList() {
      return course_;
    }
    /**
     * <pre>
     * string[] courses = 4;
     * </pre>
     *
     * <code>repeated string course = 5;</code>
     */
    public int getCourseCount() {
      return course_.size();
    }
    /**
     * <pre>
     * string[] courses = 4;
     * </pre>
     *
     * <code>repeated string course = 5;</code>
     */
    public java.lang.String getCourse(int index) {
      return course_.get(index);
    }
    /**
     * <pre>
     * string[] courses = 4;
     * </pre>
     *
     * <code>repeated string course = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCourseBytes(int index) {
      return course_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClassNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, className_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (age_ != 0) {
        output.writeInt32(3, age_);
      }
      for (int i = 0; i < course_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, course_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClassNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, className_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < course_.size(); i++) {
          dataSize += computeStringSizeNoTag(course_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getCourseList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rest.api.proto.ProtoBuffImpl.MyProtoBuff)) {
        return super.equals(obj);
      }
      rest.api.proto.ProtoBuffImpl.MyProtoBuff other = (rest.api.proto.ProtoBuffImpl.MyProtoBuff) obj;

      boolean result = true;
      result = result && getClassName()
          .equals(other.getClassName());
      result = result && getName()
          .equals(other.getName());
      result = result && (getAge()
          == other.getAge());
      result = result && getCourseList()
          .equals(other.getCourseList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLASSNAME_FIELD_NUMBER;
      hash = (53 * hash) + getClassName().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      if (getCourseCount() > 0) {
        hash = (37 * hash) + COURSE_FIELD_NUMBER;
        hash = (53 * hash) + getCourseList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rest.api.proto.ProtoBuffImpl.MyProtoBuff parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rest.api.proto.ProtoBuffImpl.MyProtoBuff parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rest.api.proto.ProtoBuffImpl.MyProtoBuff parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rest.api.proto.ProtoBuffImpl.MyProtoBuff parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rest.api.proto.ProtoBuffImpl.MyProtoBuff parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rest.api.proto.ProtoBuffImpl.MyProtoBuff parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static rest.api.proto.ProtoBuffImpl.MyProtoBuff parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static rest.api.proto.ProtoBuffImpl.MyProtoBuff parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rest.api.proto.ProtoBuffImpl.MyProtoBuff parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rest.api.proto.ProtoBuffImpl.MyProtoBuff parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rest.api.proto.ProtoBuffImpl.MyProtoBuff prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.student.MyProtoBuff}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.student.MyProtoBuff)
        rest.api.proto.ProtoBuffImpl.MyProtoBuffOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rest.api.proto.ProtoBuffImpl.internal_static_proto_student_MyProtoBuff_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rest.api.proto.ProtoBuffImpl.internal_static_proto_student_MyProtoBuff_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rest.api.proto.ProtoBuffImpl.MyProtoBuff.class, rest.api.proto.ProtoBuffImpl.MyProtoBuff.Builder.class);
      }

      // Construct using rest.api.proto.ProtoBuffImpl.MyProtoBuff.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        className_ = "";

        name_ = "";

        age_ = 0;

        course_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rest.api.proto.ProtoBuffImpl.internal_static_proto_student_MyProtoBuff_descriptor;
      }

      public rest.api.proto.ProtoBuffImpl.MyProtoBuff getDefaultInstanceForType() {
        return rest.api.proto.ProtoBuffImpl.MyProtoBuff.getDefaultInstance();
      }

      public rest.api.proto.ProtoBuffImpl.MyProtoBuff build() {
        rest.api.proto.ProtoBuffImpl.MyProtoBuff result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public rest.api.proto.ProtoBuffImpl.MyProtoBuff buildPartial() {
        rest.api.proto.ProtoBuffImpl.MyProtoBuff result = new rest.api.proto.ProtoBuffImpl.MyProtoBuff(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.className_ = className_;
        result.name_ = name_;
        result.age_ = age_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          course_ = course_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.course_ = course_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rest.api.proto.ProtoBuffImpl.MyProtoBuff) {
          return mergeFrom((rest.api.proto.ProtoBuffImpl.MyProtoBuff)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rest.api.proto.ProtoBuffImpl.MyProtoBuff other) {
        if (other == rest.api.proto.ProtoBuffImpl.MyProtoBuff.getDefaultInstance()) return this;
        if (!other.getClassName().isEmpty()) {
          className_ = other.className_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (!other.course_.isEmpty()) {
          if (course_.isEmpty()) {
            course_ = other.course_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureCourseIsMutable();
            course_.addAll(other.course_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        rest.api.proto.ProtoBuffImpl.MyProtoBuff parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (rest.api.proto.ProtoBuffImpl.MyProtoBuff) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object className_ = "";
      /**
       * <code>string className = 1;</code>
       */
      public java.lang.String getClassName() {
        java.lang.Object ref = className_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          className_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string className = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClassNameBytes() {
        java.lang.Object ref = className_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          className_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string className = 1;</code>
       */
      public Builder setClassName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        className_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string className = 1;</code>
       */
      public Builder clearClassName() {
        
        className_ = getDefaultInstance().getClassName();
        onChanged();
        return this;
      }
      /**
       * <code>string className = 1;</code>
       */
      public Builder setClassNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        className_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 3;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 3;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 3;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList course_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCourseIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          course_ = new com.google.protobuf.LazyStringArrayList(course_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <pre>
       * string[] courses = 4;
       * </pre>
       *
       * <code>repeated string course = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getCourseList() {
        return course_.getUnmodifiableView();
      }
      /**
       * <pre>
       * string[] courses = 4;
       * </pre>
       *
       * <code>repeated string course = 5;</code>
       */
      public int getCourseCount() {
        return course_.size();
      }
      /**
       * <pre>
       * string[] courses = 4;
       * </pre>
       *
       * <code>repeated string course = 5;</code>
       */
      public java.lang.String getCourse(int index) {
        return course_.get(index);
      }
      /**
       * <pre>
       * string[] courses = 4;
       * </pre>
       *
       * <code>repeated string course = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCourseBytes(int index) {
        return course_.getByteString(index);
      }
      /**
       * <pre>
       * string[] courses = 4;
       * </pre>
       *
       * <code>repeated string course = 5;</code>
       */
      public Builder setCourse(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCourseIsMutable();
        course_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * string[] courses = 4;
       * </pre>
       *
       * <code>repeated string course = 5;</code>
       */
      public Builder addCourse(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCourseIsMutable();
        course_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * string[] courses = 4;
       * </pre>
       *
       * <code>repeated string course = 5;</code>
       */
      public Builder addAllCourse(
          java.lang.Iterable<java.lang.String> values) {
        ensureCourseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, course_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * string[] courses = 4;
       * </pre>
       *
       * <code>repeated string course = 5;</code>
       */
      public Builder clearCourse() {
        course_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * string[] courses = 4;
       * </pre>
       *
       * <code>repeated string course = 5;</code>
       */
      public Builder addCourseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureCourseIsMutable();
        course_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.student.MyProtoBuff)
    }

    // @@protoc_insertion_point(class_scope:proto.student.MyProtoBuff)
    private static final rest.api.proto.ProtoBuffImpl.MyProtoBuff DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rest.api.proto.ProtoBuffImpl.MyProtoBuff();
    }

    public static rest.api.proto.ProtoBuffImpl.MyProtoBuff getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MyProtoBuff>
        PARSER = new com.google.protobuf.AbstractParser<MyProtoBuff>() {
      public MyProtoBuff parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MyProtoBuff(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MyProtoBuff> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyProtoBuff> getParserForType() {
      return PARSER;
    }

    public rest.api.proto.ProtoBuffImpl.MyProtoBuff getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_student_MyProtoBuff_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_student_MyProtoBuff_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MyProtoBuff.proto\022\rproto.student\"K\n\013My" +
      "ProtoBuff\022\021\n\tclassName\030\001 \001(\t\022\014\n\004name\030\002 \001" +
      "(\t\022\013\n\003age\030\003 \001(\005\022\016\n\006course\030\005 \003(\tB\037\n\016rest." +
      "api.protoB\rProtoBuffImplb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_student_MyProtoBuff_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_student_MyProtoBuff_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_student_MyProtoBuff_descriptor,
        new java.lang.String[] { "ClassName", "Name", "Age", "Course", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
