
package soap.api.wsimport.autogen;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceEJB_ServiceName", targetNamespace = "http://api.soap/", wsdlLocation = "file:/home/jackdaeel/IdeaProjects/MavenProjects/SoapRest/soap-api-ejb/src/main/resources/wsdl/download/SingletonSessionBeanWebService.wsdl")
public class WebServiceEJBServiceName
    extends Service
{

    private final static URL WEBSERVICEEJBSERVICENAME_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEEJBSERVICENAME_EXCEPTION;
    private final static QName WEBSERVICEEJBSERVICENAME_QNAME = new QName("http://api.soap/", "WebServiceEJB_ServiceName");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/jackdaeel/IdeaProjects/MavenProjects/SoapRest/soap-api-ejb/src/main/resources/wsdl/download/SingletonSessionBeanWebService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEEJBSERVICENAME_WSDL_LOCATION = url;
        WEBSERVICEEJBSERVICENAME_EXCEPTION = e;
    }

    public WebServiceEJBServiceName() {
        super(__getWsdlLocation(), WEBSERVICEEJBSERVICENAME_QNAME);
    }

    public WebServiceEJBServiceName(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEEJBSERVICENAME_QNAME, features);
    }

    public WebServiceEJBServiceName(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEEJBSERVICENAME_QNAME);
    }

    public WebServiceEJBServiceName(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEEJBSERVICENAME_QNAME, features);
    }

    public WebServiceEJBServiceName(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceEJBServiceName(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceEJBName
     */
    @WebEndpoint(name = "WebServiceEJB_PortName")
    public WebServiceEJBName getWebServiceEJBPortName() {
        return super.getPort(new QName("http://api.soap/", "WebServiceEJB_PortName"), WebServiceEJBName.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceEJBName
     */
    @WebEndpoint(name = "WebServiceEJB_PortName")
    public WebServiceEJBName getWebServiceEJBPortName(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.soap/", "WebServiceEJB_PortName"), WebServiceEJBName.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEEJBSERVICENAME_EXCEPTION!= null) {
            throw WEBSERVICEEJBSERVICENAME_EXCEPTION;
        }
        return WEBSERVICEEJBSERVICENAME_WSDL_LOCATION;
    }

}
